name: Advanced Windows RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Install Chocolatey and Dependencies
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex
        choco install ngrok

    - name: Configure RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        $Password = ConvertTo-SecureString "hyd12345" -AsPlainText -Force
        New-LocalUser "admin" -Password $Password -PasswordNeverExpires -UserMayNotChangePassword -AccountNeverExpires
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member "admin"

    - name: Start Ngrok Tunnel
      run: |
        ngrok authtoken ${{ secrets.NGROK_AUTHTOKEN }}
        ngrok tcp 3389 --region us -log=stdout > ngrok.log &

    - name: Fetch Ngrok Tunnel Info
      id: ngrok_info
      run: |
        Start-Sleep 10
        $log_content = Get-Content ngrok
        $url = $log_content -match 'tcp://(.+?)"'
        echo "::set-output name=url::$(($matches[1]))"

    - name: Post RDP Info to Issue
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.inputs.issue_number }}
        body: |
          🚀 RDP Session is ready!
          - Address: ${{ steps.ngrok_info.outputs.url }}
          - Username: `admin`
          - Password: `hyd12345`
